direction: up

BKT: {
  class: component
  label: BKT
}

InputData: {
  class: component
  label: Interactions \n Data
}
InputData.shape: rectangle

# 1. Embeddings Layer

EmbeddingsLayer: {
  class: layer
  Embeddings: {
    class: component
    label: |md
      Individualized Embeddings

      x'ₜ (Current Task)

      y'ₜ (History)
    |
  }

  Embeddings.shape: rectangle
}

# 3. Attention Heads (Transformer)
Transformer: {
  class: transformer

  Encoder: {
    class: component
    label: "Encoder\n(Self-Attention on y'_{1:t-1})"
  }

  Decoder: {
    class: component
    label: "Decoder\n(Cross-Attention + x'ₜ)"
  }

  # 4. Intermediate Context Vector
  zt: {
    class: component
    shape: rectangle
    label: "zₜ \n Context Vector"
    style: {
      fill: "#ffffff"
      stroke-width: 2
    }
  }

  Encoder -> Decoder: "History Context"
  Decoder -> zt
}

# 5. Output Layer
Outputs: {
  class: layer

  SupervisedOut: {
    class: component
    label: "p_res \n Supervised"
  }

  GroundedOut1: {
    class: component
    label: "p_L0 \n Grounded"
  }

  GroundedOut2: {
    class: component
    label: "p_T \n Grounded"
  }
}

# 6. Multi-objective Loss Functions

LossLayer: {
  class: layer
  LossSupervised: {class: component}
  LossRegularization: {class: component}
  LossGrounded: {class: component}
}

# Relationships / Flow
BKT -> EmbeddingsLayer.Embeddings: p_l0, p_T
InputData -> EmbeddingsLayer.Embeddings: "{(q, c, r)}"
EmbeddingsLayer.Embeddings -> Transformer.Encoder: "y'_{1:t-1}"
EmbeddingsLayer.Embeddings -> Transformer.Decoder: "x'ₜ"

Transformer.zt -> Outputs.SupervisedOut

# Loss functions
Outputs -> LossLayer

# Define Classes for visual consistency
classes: {
  layer: {
    style: {
      fill: "#ffffff"
      stroke: "#000000"
      stroke-width: 2
      border-radius: 8
      stroke-dash: 5
    }
  }

  component: {
    style: {
      fill: "#ffffff"
      stroke: "#000000"
      stroke-width: 2
    }
  }

  transformer: {
    style: {
      fill: "#ffffff"
      stroke: "#000000"
      stroke-width: 2
    }
  }
}


